spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    #    url: jdbc:mysql://localhost:3307/maysara
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

app:
  message: "Hello product from config server"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  #  level:
  #    root: INFO
  #    com.ecommerce.user: TRACE
  file:
#    name: logs/product-service.log
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5