spring:
  data:
    mongodb:
      uri: "${MONGO_URI}"
    database: userdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
#  level:
#    root: INFO
#    com.ecommerce.user: TRACE
  file:
    name: logs/user-service.log
    #name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5

